name: CyberTrenerConda
channels:
  - defaults

dependencies:
  - python=3.11
  - pip

  - pip:
      - numpy==2.4.4
      - opencv-python==4.13.0.92
      - python-dotenv==1.2.2

      - pyqt6==6.11.0
      - pyqt6-qt6==6.11.0
      - pyqt6-sip==13.11.1